### ISSUE TITLE
the basic.ino sample will brick your tracker

### ISSUE THREAD

**Issue by aguaviva** [atc1441/HRS3300-Arduino-Library#1]
That is because the sensor is not not powered, 'digitalWrite' is writing a LOW when it should write a HIGH to power it up

```
void setup(void)
{
  delay(1000);
  Serial.begin(115200);
  Serial.println("HRS3300 HRS sensor test");
  pinMode(HRSPowerPin, OUTPUT);
  digitalWrite(HRSPowerPin, LOW);
  HRS3300.begin();
}
```

Also once you flash this sketch there is no way to get back to the bootloader and you are stuck with this until you crack open the device

**Comment by atc1441** [comment]
Hi, that is a good information for someone who is new to it, 
But this is meant for an open fitness tracker where the SWD port is already connected and it can be reprogrammed.

Wanted to have it as short as possible as it can be also used in not fitness tracker devices.

Will check about the Power pin, tested it back then and it should be low to be powered if i remember correctly.

**Comment by aguaviva** [comment]
Aaron, in the readme.md you show a DSD6 tracker, I did try your code there and it got bricked. 
Others can fall in my same trap so please reopen this bug  and do not close it until you can double check and clarify things in the readme or fix the code.

**Comment by atc1441** [comment]
When you read above the image, you see that I mention it is for another heart rate sensor.

Also i mention in the linked video that you need to make sure to always have an option to go back into Bootloader Mode.

**Comment by aguaviva** [comment]
I'd be great if you could mention those two things in the readme.md.
